import type { Metadata } from "next";
// import "./globals.css";
import AdminHeader from "@/components/AdminHeader";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function AdminDashboardLayout({ children }: LayoutProps<"/">) {
  return (
    
     <div>
        <div>
            <AdminHeader />
        </div>
        {children}
     </div>
  
  );
}
